### ISSUE TITLE
Design a responsive 'about us' page

### ISSUE THREAD

**Issue by aritroCoder** [aritroCoder/ecohacks#4] opened 2022-12-01 04:45 UTC
A nice and simplistic design for the about us page will be appreciated.
Note: For this PR you might use any random text to fill in the about us page

**Comment by Babieshark** [comment] 2022-12-05 09:25
I want to try this. Please assign it to me. Also, please explain what content/features etc. You want in the page.

**Comment by aritroCoder** [comment] 2022-12-05 10:44
> I want to try this. Please assign it to me. Also, please explain what content/features etc. You want in the page.

See, here I don't really focus on content as I said in the first comment. All I want is a nice about us page. For ideas, you can visit different about us pages in other websites. Broadly speaking, it may contain a description section, where we describe what the website is about, a team section maybe where the team members working on the project can be listed, a contact section where contact details are present. You can use your creativity to add/remove sections

**Comment by SattyamSamania** [comment] 2022-12-05 14:50
Hey @aritroCoder Can I also work on this issue?

**Comment by aritroCoder** [comment] 2022-12-05 16:30
> Hey @aritroCoder Can I also work on this issue?

Sorry I have already assigned this issue to another contributor. There are some more unassigned issue left, you can try them

**Comment by sankooru14** [comment] 2022-12-07 03:57
@aritroCoder  can you assign this to me?

**Comment by aritroCoder** [comment] 2022-12-07 07:08
> @aritroCoder can you assign this to me?

Sorry this issue is assigned and the assignee is actively working

**Comment by Tushar98644** [comment] 2022-12-15 19:14
assign me @aritroCoder if the issue is still open

**Comment by aritroCoder** [comment] 2022-12-16 03:51
> assign me @aritroCoder if the issue is still open

The assignee is working in this issue

**Comment by Tushar98644** [comment] 2022-12-26 06:37
It's been 3 weeks...i don't think anyone is working on it ....kindly assign @aritroCoder

**Comment by aritroCoder** [comment] 2022-12-26 09:41
> It's been 3 weeks...i don't think anyone is working on it ....kindly assign @aritroCoder

Okay take up the issue

**Closed as completed** 2022-12-27 06:03 UTC
Labels: enhancement, codepeak, frontend, medium
